Launching middleware required in testing with docker
personium/personium-engine pull request #128
Opened 2020-10-29 08:33 UTC by yoh1496

There are middleware needed to run test of `personium-engine`

- ElasticSearch
- ActiveMQ
- memcached
- nginx
- Tomcat

I write docker-compose to launch them excepting Tomcat.
( You need launch Tomcat locally and deploy `personium-core` there )

How about this?

2020-10-30 02:29 UTC, dixonsiu requested changes
Please check my suggestion.

Good job! Thank you for making personium-engine better.

2020-10-30 02:29 UTC, dixonsiu commented on README.md
> +1. Launch prequire software with `docker-compose up`
```suggestion
1. Launch required software with `docker-compose up`
```

2020-10-30 02:29 UTC, dixonsiu commented on README.md
> +1. Launch tomcat9 locally
```suggestion
1. Launch tomcat9 locally  
`systemctl start tomcat`
```

2020-10-30 02:29 UTC, dixonsiu commented on README.md
> +1. Launch tomcat9 locally
It is more friendly to provide a sample command. Please use the correct tomcat service name when you reflect on the change.

2020-10-30 02:29 UTC, dixonsiu commented on README.md
> +1. Deploy `personium-core` tomcat locally with option `io.personium.core.pathBasedCellUrl.enabled=true`
How to deploy? What are the procedures/commands?

2020-10-30 02:29 UTC, dixonsiu commented on README.md
> +1. Execute tests with maven.
Can you provide the maven command?

2020-11-02 02:07 UTC, shimono approved these changes
Thanks a lot.

2021-01-08 10:11 UTC, yoh1496 reviewed
I updated. Could you check this?

2021-01-08 10:11 UTC, yoh1496 commented on README.md
> +1. Launch tomcat9 locally
I'll write launch and deploy command

2021-01-12 01:00 UTC, dixonsiu approved these changes

2021-01-14 01:58 UTC, tochi-y requested changes

2021-01-14 01:58 UTC, tochi-y commented on README.md
> +    mvn -f pom.xml
```suggestion
    mvn -f pom.xml test
```

I think if no specifying phase, package, install and deploy phase are executed.

2021-01-14 02:29 UTC, tochi-y approved these changes

2021-01-14 02:29 UTC, merged