Bug fix.
personium/personium-engine pull request #48
Opened 2018-03-20 05:40 UTC by SawamiWataru

2018-03-20 05:52 UTC, dixonsiu requested changes

2018-03-20 05:52 UTC, dixonsiu commented on src/main/resources/js-lib/personium-dao.js
> +                        if (principalObj instanceof Packages.io.personium.client.Principal) {
Where did you get principalObj?

2018-03-20 06:08 UTC, SawamiWataru commented on src/main/resources/js-lib/personium-dao.js
> +                        if (principalObj instanceof Packages.io.personium.client.Principal) {
I corrected it to the correct variable.

2018-03-23 00:20 UTC, dixonsiu approved these changes

2018-03-23 02:09 UTC, merged